gam: update to 7.34.02
Changes from 7.33.02:

Updated GAM to prevent errors like the following:

ERROR: Unable to find the server at oauth2.googleapis.com
ERROR: Unable to find the server at gmail.googleapis.com

7.34.01

Updated gam create|update adminrole to handle the following errors:

ERROR: 400: invalid - Invalid Role privileges
ERROR: 400: required - Required parameter: [resource.privileges[n].service_id]

7.34.00

Added variable csv_output_header_required to gam.cfg that is a comma separated list of <Strings> that are required to be in the list of column headers in the CSV file written by a gam print command. This will typically be used to specify headers that are required in subsequent commands that process the CSV file even if the API didn't return any data for those columns.

Updated the following commands to not require the Directory API - Domains scope unless the internal or external options are used to request the member category.

gam info|print groups
gam print|show group-members
gam info|print cigroups
gam print|show cigroup-members
gam <UserTypeEntity> print|show filesharecounts

7.33.03

Fixed bug in gam [<UserTypeEntity>] sendemail ... from <EmailAddress> replyto <EmailAddress> where an <EmailAddress> of the form Text <user@domain.com> had the Text removed.