math/py-numpy: Tweak workaround for missing log2l/log1pl/expm1l.
1. Put it in npy_math.c as needed by _umath_linalg.so.

2. Limit it to NetBSD<10, since NetBSD>=10 has at least stubs (just
   like this workaround implements, in terms of double functions) if
   not proper long double implementations (NetBSD>=11).

Fixes:

>>> import numpy
...
ImportError: /home/riastradh/pkgsrc/current/pkg/lib/python3.11/site-packages/numpy/linalg/_umath_linalg.so: Undefined PLT symbol "log1pl" (symnum = 20)

PR pkg/60256: devel/py-numpy: log1pl workaround no longer works around